cp gibbergen0.maxpat gibbergen1.maxpat 
cp gibbergen0.maxpat gibbergen2.maxpat 
cp gibbergen0.maxpat gibbergen3.maxpat 
cp gibbergen0.maxpat gibbergen4.maxpat 
cp gibbergen0.maxpat gibbergen5.maxpat 
cp gibbergen0.maxpat gibbergen6.maxpat 
cp gibbergen0.maxpat gibbergen7.maxpat 
cp gibbergen0.maxpat gibbergen8.maxpat 
cp gibbergen0.maxpat gibbergen9.maxpat 
cp gibbergen0.maxpat gibbergen10.maxpat 
cp gibbergen0.maxpat gibbergen11.maxpat 
cp gibbergen0.maxpat gibbergen12.maxpat 
cp gibbergen0.maxpat gibbergen13.maxpat 
cp gibbergen0.maxpat gibbergen14.maxpat 
cp gibbergen0.maxpat gibbergen15.maxpat 