cp gibbergen0.maxpat gibbergen1.maxpat 
cp gibbergen0.maxpat gibbergen2.maxpat 
cp gibbergen0.maxpat gibbergen3.maxpat 
cp gibbergen0.maxpat gibbergen4.maxpat 
cp gibbergen0.maxpat gibbergen5.maxpat 
cp gibbergen0.maxpat gibbergen6.maxpat 
cp gibbergen0.maxpat gibbergen7.maxpat 
cp gibbergen0.maxpat gibbergen8.maxpat 
cp gibbergen0.maxpat gibbergen9.maxpat 
cp gibbergen0.maxpat gibbergen10.maxpat 
cp gibbergen0.maxpat gibbergen11.maxpat 
cp gibbergen0.maxpat gibbergen12.maxpat 
cp gibbergen0.maxpat gibbergen13.maxpat 
cp gibbergen0.maxpat gibbergen14.maxpat 
cp gibbergen0.maxpat gibbergen15.maxpat 
cp gibbergen0.maxpat gibbergen16.maxpat 
cp gibbergen0.maxpat gibbergen17.maxpat 
cp gibbergen0.maxpat gibbergen18.maxpat 
cp gibbergen0.maxpat gibbergen19.maxpat 
cp gibbergen0.maxpat gibbergen20.maxpat 
cp gibbergen0.maxpat gibbergen21.maxpat 
cp gibbergen0.maxpat gibbergen22.maxpat 
cp gibbergen0.maxpat gibbergen23.maxpat 
cp gibbergen0.maxpat gibbergen24.maxpat 
cp gibbergen0.maxpat gibbergen25.maxpat 
cp gibbergen0.maxpat gibbergen26.maxpat 
cp gibbergen0.maxpat gibbergen27.maxpat 
cp gibbergen0.maxpat gibbergen28.maxpat 
cp gibbergen0.maxpat gibbergen29.maxpat 
cp gibbergen0.maxpat gibbergen30.maxpat 
cp gibbergen0.maxpat gibbergen31.maxpat 